export const copy = {
  ar: {
    nav: { menu: "القائمة", table: "حجز طاولة", orders: "طلباتي", about: "من نحن" },
    hero: {
      eyebrow: "مطعمي — مطبخ موسمي",
      title: "نكهات تُطهى على مهل، تصل إليك في دقائق",
      subtitle:
        "من فرن الحطب إلى بابك؛ أطباق مطهوة بعناية بمكونات محلية طازجة كل يوم.",
      ctaPrimary: "اطلب الآن",
      ctaSecondary: "تصفح القائمة",
      stat1Label: "تقييم العملاء",
      stat2Label: "متوسط وقت التوصيل",
    },
    promo: {
      title: "عروض اليوم",
      subtitle: "خصومات لفترة محدودة على أطباق مختارة",
    },
    categories: { title: "تصفح حسب الصنف" },
    popular: {
      title: "الأكثر طلبًا",
      subtitle: "الأطباق التي يعود إليها عملاؤنا مرارًا",
      addToCart: "أضف للسلة",
      viewDetails: "التفاصيل",
    },
    menu: {
      title: "قائمتنا الكاملة",
      subtitle: "تصفح كل الأصناف، أو ابحث عن طبق بعينه",
      searchPlaceholder: "ابحث عن طبق...",
      searchNoResults: "لا توجد نتائج مطابقة",
      searchRecent: "عمليات بحث سابقة",
      searchSuggestions: "اقتراحات",
      allCategories: "الكل",
      filters: "الفلاتر",
      filtersApply: "تطبيق الفلاتر",
      filtersReset: "إعادة تعيين",
      filterPrice: "السعر الأقصى",
      filterRating: "التقييم الأدنى",
      filterPopular: "الأكثر طلبًا",
      filterOffers: "عروض",
      filterVegetarian: "نباتي",
      filterSpicy: "حار",
      filterAvailable: "متوفر فقط",
      sortLabel: "ترتيب حسب",
      sortRecommended: "مقترح",
      sortPriceAsc: "السعر: من الأقل",
      sortPriceDesc: "السعر: من الأعلى",
      sortRating: "الأعلى تقييمًا",
      sortPrepTime: "الأسرع تحضيرًا",
      emptyTitle: "لم نجد أطباقًا مطابقة",
      emptyDescription: "جرّب تعديل الفلاتر أو مصطلح البحث",
      errorTitle: "تعذّر تحميل القائمة",
      errorDescription: "حدث خطأ أثناء الاتصال بالخادم",
      retry: "إعادة المحاولة",
      loadMore: "عرض المزيد",
      resultsCount: "نتيجة",
    },
    product: {
      ingredients: "المكونات",
      nutrition: "القيم الغذائية",
      calories: "سعرة حرارية",
      protein: "بروتين",
      carbs: "كربوهيدرات",
      fat: "دهون",
      prepTime: "وقت التحضير",
      chooseSize: "اختر الحجم",
      addExtras: "إضافات",
      quantity: "الكمية",
      addToCart: "أضف للسلة",
      unavailable: "غير متوفر حاليًا",
      total: "الإجمالي",
      reviews: "التقييمات",
      basedOn: "بناءً على",
      ratingsWord: "تقييم",
      relatedProducts: "قد يعجبك أيضًا",
      backToMenu: "العودة للقائمة",
      addedToCart: "تمت الإضافة للسلة",
    },
    cart: {
      title: "سلة الطلبات",
      emptyTitle: "سلتك فارغة",
      emptyDescription: "تصفح القائمة وأضف أطباقك المفضلة",
      browseMenu: "تصفح القائمة",
      remove: "إزالة",
      size: "الحجم",
      extras: "إضافات",
      couponPlaceholder: "أدخل كود الخصم",
      couponApply: "تطبيق",
      couponApplied: "تم تطبيق الكوبون",
      couponInvalid: "الكود غير صحيح",
      couponMinSubtotal: "الحد الأدنى للطلب",
      couponRemove: "إزالة الكوبون",
      itemsSubtotal: "المجموع الفرعي",
      discount: "الخصم",
      deliveryFee: "رسوم التوصيل",
      freeDelivery: "توصيل مجاني",
      vat: "ضريبة القيمة المضافة",
      grandTotal: "الإجمالي الكلي",
      estimatedDelivery: "وقت التوصيل المتوقع",
      estimatedDeliveryValue: "25–35 دقيقة",
      checkout: "إتمام الطلب",
      itemsCount: "صنف",
    },
    checkout: {
      title: "إتمام الطلب",
      customerInfo: "بيانات التواصل",
      fullName: "الاسم الكامل",
      phone: "رقم الجوال",
      city: "المدينة",
      district: "الحي",
      address: "العنوان التفصيلي",
      notes: "ملاحظات الطلب (اختياري)",
      notesPlaceholder: "مثال: بدون بصل، اترك الطلب عند الباب...",
      deliveryMethod: "طريقة الاستلام",
      pickup: "استلام من المطعم",
      pickupHint: "جاهز خلال 15–20 دقيقة",
      delivery: "توصيل",
      deliveryHint: "يصل خلال 25–35 دقيقة",
      paymentMethod: "طريقة الدفع",
      orderReview: "مراجعة الطلب",
      placeOrder: "تأكيد الطلب",
      placingOrder: "جارٍ إرسال الطلب...",
      errorRequired: "هذا الحقل مطلوب",
      errorTooShort: "قصير جدًا",
      errorInvalidPhone: "رقم جوال سعودي غير صحيح",
      paymentCash: "الدفع عند الاستلام",
      paymentMada: "مدى",
      paymentVisa: "فيزا",
      paymentMastercard: "ماستركارد",
      paymentApplePay: "Apple Pay",
      paymentStcPay: "STC Pay",
      paymentBankTransfer: "تحويل بنكي",
    },
    orderConfirmation: {
      success: "تم استلام طلبك",
      orderNumber: "رقم الطلب",
      estimatedTime: "الوقت المتوقع للتحضير",
      minutes: "دقيقة",
      trackOrder: "تتبع الطلب",
      backHome: "العودة للرئيسية",
      sendWhatsApp: "إرسال الطلب عبر واتساب",
      orderSummary: "ملخص الطلب",
      notFoundTitle: "الطلب غير موجود",
      notFoundDescription: "تعذر العثور على هذا الطلب.",
    },
    orderHistory: {
      title: "طلباتي",
      empty: "لا توجد طلبات سابقة بعد",
      viewOrder: "عرض الطلب",
    },
    footer: {
      tagline: "طهي هادئ، بلا استعجال — إلا في التوصيل.",
      rights: "جميع الحقوق محفوظة",
    },
  },
  en: {
    nav: { menu: "Menu", table: "Book a Table", orders: "My Orders", about: "About" },
    hero: {
      eyebrow: "مطعمي — Seasonal Kitchen",
      title: "Slow-cooked flavor, delivered in minutes",
      subtitle:
        "From the wood-fired oven to your door — dishes crafted daily with fresh, local ingredients.",
      ctaPrimary: "Order Now",
      ctaSecondary: "View Menu",
      stat1Label: "Customer Rating",
      stat2Label: "Avg. Delivery Time",
    },
    promo: {
      title: "Today's Offers",
      subtitle: "Limited-time discounts on selected dishes",
    },
    categories: { title: "Browse by Category" },
    popular: {
      title: "Popular Right Now",
      subtitle: "The dishes our regulars keep coming back for",
      addToCart: "Add to Cart",
      viewDetails: "Details",
    },
    menu: {
      title: "Our Full Menu",
      subtitle: "Browse every category, or search for something specific",
      searchPlaceholder: "Search for a dish...",
      searchNoResults: "No matching results",
      searchRecent: "Recent searches",
      searchSuggestions: "Suggestions",
      allCategories: "All",
      filters: "Filters",
      filtersApply: "Apply Filters",
      filtersReset: "Reset",
      filterPrice: "Max Price",
      filterRating: "Min Rating",
      filterPopular: "Popular",
      filterOffers: "Offers",
      filterVegetarian: "Vegetarian",
      filterSpicy: "Spicy",
      filterAvailable: "Available only",
      sortLabel: "Sort by",
      sortRecommended: "Recommended",
      sortPriceAsc: "Price: Low to High",
      sortPriceDesc: "Price: High to Low",
      sortRating: "Top Rated",
      sortPrepTime: "Fastest Prep",
      emptyTitle: "No dishes match your filters",
      emptyDescription: "Try adjusting the filters or your search term",
      errorTitle: "Couldn't load the menu",
      errorDescription: "Something went wrong while contacting the server",
      retry: "Try Again",
      loadMore: "Load More",
      resultsCount: "results",
    },
    product: {
      ingredients: "Ingredients",
      nutrition: "Nutrition Facts",
      calories: "Calories",
      protein: "Protein",
      carbs: "Carbs",
      fat: "Fat",
      prepTime: "Prep Time",
      chooseSize: "Choose Size",
      addExtras: "Extras",
      quantity: "Quantity",
      addToCart: "Add to Cart",
      unavailable: "Currently Unavailable",
      total: "Total",
      reviews: "Reviews",
      basedOn: "Based on",
      ratingsWord: "ratings",
      relatedProducts: "You Might Also Like",
      backToMenu: "Back to Menu",
      addedToCart: "Added to cart",
    },
    cart: {
      title: "Your Cart",
      emptyTitle: "Your cart is empty",
      emptyDescription: "Browse the menu and add your favorite dishes",
      browseMenu: "Browse Menu",
      remove: "Remove",
      size: "Size",
      extras: "Extras",
      couponPlaceholder: "Enter coupon code",
      couponApply: "Apply",
      couponApplied: "Coupon applied",
      couponInvalid: "Invalid code",
      couponMinSubtotal: "Minimum order",
      couponRemove: "Remove coupon",
      itemsSubtotal: "Subtotal",
      discount: "Discount",
      deliveryFee: "Delivery Fee",
      freeDelivery: "Free delivery",
      vat: "VAT",
      grandTotal: "Grand Total",
      estimatedDelivery: "Estimated Delivery",
      estimatedDeliveryValue: "25–35 min",
      checkout: "Proceed to Checkout",
      itemsCount: "items",
    },
    checkout: {
      title: "Checkout",
      customerInfo: "Contact Details",
      fullName: "Full Name",
      phone: "Phone Number",
      city: "City",
      district: "District",
      address: "Detailed Address",
      notes: "Order Notes (optional)",
      notesPlaceholder: "e.g. no onions, leave at the door...",
      deliveryMethod: "Delivery Method",
      pickup: "Pickup",
      pickupHint: "Ready in 15–20 min",
      delivery: "Delivery",
      deliveryHint: "Arrives in 25–35 min",
      paymentMethod: "Payment Method",
      orderReview: "Order Review",
      placeOrder: "Confirm Order",
      placingOrder: "Placing your order...",
      errorRequired: "This field is required",
      errorTooShort: "Too short",
      errorInvalidPhone: "Invalid Saudi phone number",
      paymentCash: "Cash on Delivery",
      paymentMada: "Mada",
      paymentVisa: "Visa",
      paymentMastercard: "MasterCard",
      paymentApplePay: "Apple Pay",
      paymentStcPay: "STC Pay",
      paymentBankTransfer: "Bank Transfer",
    },
    orderConfirmation: {
      success: "Order Received",
      orderNumber: "Order Number",
      estimatedTime: "Estimated Prep Time",
      minutes: "min",
      trackOrder: "Track Order",
      backHome: "Back Home",
      sendWhatsApp: "Send Order via WhatsApp",
      orderSummary: "Order Summary",
      notFoundTitle: "Order not found",
      notFoundDescription: "We couldn't find this order.",
    },
    orderHistory: {
      title: "My Orders",
      empty: "No past orders yet",
      viewOrder: "View Order",
    },
    footer: {
      tagline: "Unhurried cooking — delivered without the wait.",
      rights: "All rights reserved",
    },
  },
} as const;

export type Locale = keyof typeof copy;
